[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"  # 如果有serverless functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173  # Vite默认端口
  publish = "dist"