[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://website-security-back-production.up.railway.app"

[context.production.environment]  
  VITE_API_BASE_URL = "https://website-security-back-production.up.railway.app"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://website-security-back-production.up.railway.app"

[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://website-security-back-production.up.railway.app"